# Site settings
title: Be a Better Leader
header-img: img/home-bg.jpg
email: jelena.barinovas@gmail.com
description: "Practical notes on leadership improvements"
baseurl: /BeBetterLeader
url: "http://jelenabarinova.github.io"
github: 
twitter_username: jfiodorova
github_username:  JelenaBarinova
facebook_username:  jelena.fiodorova
linkedin_username: jelenabarinova
google_tracking_id: UA-39383708-1
disqus_shortname: bebetterleader
# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
paginate: 10
exclude: ["less","node_modules","package.json","README.md"]

collections:
  docs:
    output: true
