# Site settings
title: Be a Better Leader
header-img: img/home-bg.jpg
email: jelena.barinovas@gmail.com
description: "Practical notes on leadership improvements"
baseurl: "/BeBetterLeader"
url: "http://jelenabarinova.github.io"
github: 
twitter_username: jfiodorova
github_username:  JelenaBarinova
facebook_username:  jelena.fiodorova

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","gulpfilee.js","package.json","README.md"]
